Issue/90 allow skip on connect failure
inmanta/vyos pull request #91
Opened 2020-09-29 13:20 UTC by sanderr

# Description

Added the option to skip resources when host connection fails

closes #90

# Merge procedure

Don't use the github built-in merge, but the process described [here](https://docs.internal.inmanta.com/topics/tasks/commiting_changes_modules.html)

```sh
git pull
git checkout master
git pull
git merge --squash issue/{issue-number}-{short description}
inmanta module commit -m "{Commit Message Here}" -r
git push
git push {tag} # push the tag as well
```

Then close the PR with a reference to the commit

# Self Check:

Strike through any lines that are not applicable (`~~line~~`) then check the box

- [x] Attached issue to pull request
- [x] Changelog entry
- [x] Version number is bumped to dev version
- [x] Code is clear and sufficiently documented
- [x] ~~Sufficient test cases (reproduces the bug/tests the requested feature)~~
- [x] Correct, in line with design
- [x] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~

# Reviewer Checklist:

- [ ] Sufficient test cases (reproduces the bug/tests the requested feature)
- [ ] Code is clear and sufficiently documented
- [ ] Correct, in line with design

2020-09-29 13:31 UTC, wouterdb requested changes

2020-09-29 13:31 UTC, wouterdb commented on model/_init.cf
> +        skip_on_connect_error=self.host.skip_on_connect_error,
would it no have been easier to do this self.host.skip_on_connect_error purely in the resource? (i.e. make the field on the python resource, not on the model resource)

2020-09-29 14:53 UTC, sanderr commented on model/_init.cf
> +        skip_on_connect_error=self.host.skip_on_connect_error,
I chose to mimic how it's done for `host.name`. Doing it like you suggest would require adding a relation to the host, right? I agree that would be a bit cleaner, but less consistent. My preference is only slight so I'm willing to changes this if you wish.

2020-09-29 14:55 UTC, wouterdb approved these changes

2020-10-01 10:10 UTC, bartv approved these changes

2020-10-01 10:19 UTC, sanderr commented
Merged in 8cd1a0c

2020-10-01 10:20 UTC, closed without merging